---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre-web
      version: 8.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    podSecurityContext: 
      fsGroup: 100
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "bookshelf"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "books.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "books.${SECRET_DOMAIN}"
            secretName: "calibre-web-tls"
    persistence:
      config:
        storageClass: nfs-client
        size: 200Mi
        enabled: true
      books:
        existingClaim: nfs-share-books-pvc
        enabled: true
