---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share-books-pv
spec:
  storageClassName: nfs-share-books
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.200
    path: /volume1/cluster/share/media/books/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-share-books-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-share-books
  resources:
    requests:
      storage: 10Gi
