---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: searx
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: searx
      version: 5.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      - name: SEARX_MORTY_KEY
        valueFrom:
          secretKeyRef:
            name: searx-secrets
            key: searx_morty_key
    searx:
      baseUrl: "searx.${SECRET_DOMAIN}"
      mortyKey: "${SEARX_MORTY_KEY}"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "search-web"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "searx.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "searx.${SECRET_DOMAIN}"
            secretName: "searx-tls"
