---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniflux-db
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 20Gi
