---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: miniflux
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: miniflux
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      ADMIN_USERNAME: pgrauman
      TZ: "America/New_York"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "rss"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "rss.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "rss.${SECRET_DOMAIN}"
            secretName: "miniflux-tls"
    postgresql:
      persistence:
        enabled: true
        storageClass: nfs-client
        size: 10Gi
      primary:
        nodeSelector:
          kubernetes.io/arch: amd64
