---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate:
      chart: nfs-subdir-external-provisioner
      version: "4.0.14"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner
      tag: v4.0.2
    storageClass:
      name: nfs-client
      reclaimPolicy: Retain
      pathPattern: "${.PVC.namespace}/${.PVC.name}"
    nfs:
      server: "192.168.0.200"
      path: /volume1/cluster
      reclaimPolicy: "Retain"
