---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: kube-system
  labels:
    kustomize.toolkit.fluxcd.io/substitute: "disabled"
spec:
  interval: 5m
  chart:
    spec:
      # renovate:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      chart: nfs-subdir-external-provisioner
      version: 4.0.14
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner-charts
        namespace: flux-system
      interval: 5m
  values:
    storageClass:
      defaultClass: false
      name: nfs-client
      reclaimPolicy: Retain
      pathPattern: "${.PVC.namespace}/${.PVC.name}"
    nfs:
      server: "192.168.0.200"
      path: /volume1/cluster
      reclaimPolicy: "Retain"
