---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: syncthing
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: syncthing
      version: 3.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    nodeSelector:
      kubernetes.io/arch: arm64
    podSecurityContext: 
      runAsUser: 1026
      runAsGroup: 100
      fsGroup: 100
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "folder-sync"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "syncthing.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "syncthing.${SECRET_DOMAIN}"
            secretName: "syncthing-tls"
    persistence:
      data:
        existingClaim: nfs-share-pvc
        enabled: true
