---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share-pv
spec:
  storageClassName: share-data
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.200
    path: /volume1/cluster/share
  mountOptions:
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-share-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: share-data
  resources:
    requests:
      storage: 10Gi
